;20260327_Version:B2

[custom]
;ruleset=全球直连,clash-classic:https://cdn.jsdelivr.net/gh/whengrun/Rule@master/Clash-User/Providers/UserRule-Clash-DIRECT.yaml,43200
ruleset=全球直连,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash-User/Providers/UserRule-Clash-DIRECT.yaml,43200
ruleset=全球直连,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/LocalAreaNetwork.yaml,43200
ruleset=台湾服务,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash-User/Providers/UserRule-TW.yaml,43200
ruleset=地域定位,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash-User/Providers/UserRule-pc.yaml,43200
ruleset=地域定位,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash-User/Providers/UserRule-Clash.yaml,43200
ruleset=全球拦截,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash-User/Providers/UserRule-block.yaml,43200
ruleset=全球直连,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/UnBan.yaml,43200
ruleset=全球拦截,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/BanAD.yaml,43200
ruleset=应用净化,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/BanProgramAD.yaml,43200
ruleset=全球直连,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Ruleset/GoogleCN.yaml,43200
ruleset=全球直连,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Ruleset/SteamCN.yaml,43200
ruleset=Steam服务,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Ruleset/Steam.yaml,43200
ruleset=AI平台,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Ruleset/AI.yaml,43200
ruleset=微软服务,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Ruleset/Microsoft.yaml,43200
ruleset=苹果服务,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Apple.yaml,43200
ruleset=电报信息,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Ruleset/Telegram.yaml,43200
ruleset=国外媒体,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/ProxyMedia.yaml,43200
ruleset=地域定位,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/Ruleset/Porn.yaml,43200
ruleset=地域定位,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/ProxyLite.yaml,43200
ruleset=全球直连,clash-classic:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/ChinaDomain.yaml,43200
ruleset=全球直连,clash-ipcidr:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/ChinaCompanyIp.yaml,43200
ruleset=全球直连,clash-ipcidr:https://raw.githubusercontent.com/whengrun/Rule/master/Clash/Providers/ChinaIp.yaml,43200
;ruleset=全球直连,[]GEOIP,LAN
ruleset=全球直连,[]GEOIP,CN
ruleset=漏网之鱼,[]FINAL

custom_proxy_group=地域定位`select`[]落地灯塔`[]落地坡县`[]落地港岛(普通)`[]落地港岛(特别)`[]落地霓虹(普通)`[]落地霓虹(特别)`[]落地湾湾`[]全球漫游`[]全球无痕`[]DIRECT`
custom_proxy_group=全球无痕`select`(无痕)
custom_proxy_group=落地灯塔`url-test`(^(?=.*(美国|US))(?!.*(无痕)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=落地坡县`url-test`(新加坡|SG|狮城)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=落地港岛(普通)`url-test`(^(?=.*(香港|HK))(?!.*(无痕|宽频|边缘)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=落地港岛(特别)`select`(^(?=.*(香港|HK))(?=.*(宽频|边缘)).*)
custom_proxy_group=落地霓虹(普通)`url-test`(^(?=.*(日本|JP))(?!.*(无痕|宽频|边缘|星链|蜂窝)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=落地霓虹(特别)`select`(^(?=.*(日本|JP))(?=.*(宽频|边缘|星链|蜂窝)).*)
custom_proxy_group=落地湾湾`url-test`(台湾|TW|臺灣|台灣)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=全球漫游`select`(^(?!.*(美国|US|新加坡|SG|狮城|香港|HK|日本|JP|台湾|TW|臺灣|台灣|懒人)).*)
custom_proxy_group=国外媒体`select`[]地域定位`[]落地灯塔`[]落地坡县`[]落地港岛(普通)`[]落地港岛(特别)`[]落地霓虹(普通)`[]落地霓虹(特别)`[]落地湾湾`[]全球漫游`[]全球无痕
custom_proxy_group=电报信息`select`[]地域定位`[]落地灯塔`[]落地坡县`[]落地港岛(普通)`[]落地港岛(特别)`[]落地霓虹(普通)`[]落地霓虹(特别)`[]落地湾湾`[]全球漫游`[]全球无痕
custom_proxy_group=AI平台`select`[]地域定位`[]落地灯塔`[]落地坡县`[]落地港岛(普通)`[]落地港岛(特别)`[]落地霓虹(普通)`[]落地霓虹(特别)`[]落地湾湾`[]全球漫游`[]全球无痕
custom_proxy_group=台湾服务`select`[]落地湾湾`[]全球直连`[]地域定位`
custom_proxy_group=微软服务`select`[]全球直连`[]地域定位`
custom_proxy_group=苹果服务`select`[]全球直连`[]地域定位`
custom_proxy_group=Steam服务`select`[]全球直连`[]地域定位`
custom_proxy_group=全球直连`select`[]DIRECT.*
custom_proxy_group=全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=漏网之鱼`select`[]全球直连`[]落地灯塔`[]落地坡县`[]落地港岛(普通)`[]落地港岛(特别)`[]落地霓虹(普通)`[]落地霓虹(特别)`[]落地湾湾`[]全球漫游`[]全球无痕

; custom_proxy_group=苹果服务`url-test`(美国|US)`http://www.gstatic.com/generate_204`300,5,100
; 表示创建一个叫 苹果服务 的 url-test 策略组,并向其中添加名字含'美国','US'的节点，每隔300秒测试一次，测速超时为5s，切换节点的延迟容差为100ms
;custom_proxy_group=🇯🇵 日本延迟最低`url-test`(日|JP)`http://www.gstatic.com/generate_204`300,5
; 表示创建一个叫 🇯🇵 日本延迟最低 的 url-test 策略组,并向其中添加名字含'日','JP'的节点，每隔300秒测试一次，测速超时为5s
; custom_proxy_group=负载均衡`load-balance`.*`http://www.gstatic.com/generate_204`300,,100
; 表示创建一个叫 负载均衡 的 load-balance 策略组,并向其中添加所有的节点，每隔300秒测试一次，切换节点的延迟容差为100ms
; custom_proxy_group=🇯🇵 JP`select`沪日`日本`[]🇯🇵 日本延迟最低
; 表示创建一个叫 🇯🇵 JP 的 select 策略组,并向其中**依次**添加名字含'沪日','日本'的节点，以及引用上述所创建的 🇯🇵 日本延迟最低 策略组
; custom_proxy_group=g1`select`!!GROUPID=0`!!INSERT=0
; 指订阅链接中的第一条订阅以及配置文件中 insert_url 中的第一条节点
; custom_proxy_group=g2`select`!!GROUPID=1
; 指订阅链接中的第二条订阅
; custom_proxy_group=g2`select`!!GROUPID=!2
; 指除了订阅链接中的第三条订阅
; custom_proxy_group=g2`select`!!GROUPID=3-5
; 指订阅链接中的第四条到第六条订阅
; custom_proxy_group=v2ray`select`!!GROUP=V2RayProvider
; 指订阅链接中组名（tag）为 V2RayProvider 的节点
; custom_proxy_group=g1hk`select`!!GROUPID=0!!(HGC|HKBN|PCCW|HKT|hk|港)
; 订阅链接中的第一条订阅内名字含 HGC、HKBN、PCCW、HKT、hk、港 的节点
; custom_proxy_group=地域定位`select`(^(?!.*(美国|日本)).*)
; 表示创建一个叫 地域定位 的 select 策略组,并向其中**依次**添加名字不包含'美国'或'日本'的节点

enable_rule_generator=true
overwrite_original_rules=true